#!/usr/bin/env python3

import pandas as pd
import pyautogui
import time
import subprocess
import sys

# Safety Failsafe: Moving your mouse to the top-left pixel instantly kills execution
pyautogui.FAILSAFE = True

def run_keyboard_sync(tsv_path):
    try:
        df = pd.read_csv(tsv_path, sep="\t")
    except FileNotFoundError:
        print(f"Error: Could not find file {tsv_path}")
        sys.exit(1)

    print("=" * 60)
    print("🚀 UBUNTU CHROME KEYBOARD EMULATOR STARTING")
    print("=" * 60)
    print("Starting in 5 seconds... Maximize Google Chrome now!")
    time.sleep(5)

    for index, row in df.iterrows():
        work_id = row['Work id']
        book_id = row['Book Id']
        barcode = row['Barcode']
        # Reading the LCC+Year string generated by your staging script
        other_call = row['LC Classification'] 
        title = row.get('Title', 'Unknown Title')

        print(f"[{index + 1}/{len(df)}] Automating '{title[:20]}...{barcode} {other_call}'")

        # Open the specific copy editor page directly in Google Chrome
        url = f"https://www.librarything.com/work/{work_id}/edit/{book_id}"
        subprocess.Popen(['google-chrome', url])
        time.sleep(4.0) # Wait for page to render fully

        # Safe area click to bring Chrome window to the active focus layer
        pyautogui.click(x=500, y=85)
        time.sleep(0.1)

        # --- FIELD 1: BARCODE ---
        pyautogui.hotkey('ctrl', 'f')
        time.sleep(0.3)
        pyautogui.write('Barcode')
        time.sleep(0.3)
        pyautogui.press('escape') # Close the find dialog overlay
        time.sleep(0.2)
        pyautogui.press('tab')    # Step from text label directly into the entry field
        time.sleep(0.1)
        
        # Clear existing text and write the code
        #pyautogui.hotkey('ctrl', 'a')
        #pyautogui.press('backspace')
        pyautogui.write(str(barcode))
        time.sleep(0.2)

        # --- FIELD 2: LC CALL NUMBER ---
        pyautogui.hotkey('ctrl', 'f')
        time.sleep(0.3)
        pyautogui.write('LC Classification')
        time.sleep(0.3)
        pyautogui.press('escape') # Close the find dialog overlay
        time.sleep(0.2)
        pyautogui.press('tab')    # Step from text label directly into the entry field
        time.sleep(0.1)
        
        # Clear existing text and write your custom LCC + Year string
        #pyautogui.hotkey('ctrl', 'a')
        #pyautogui.press('backspace')
        pyautogui.write(str(other_call))
        time.sleep(0.2)

        # --- SAVE AND CLOSE ---
        pyautogui.hotkey('ctrl', 'f')
        time.sleep(0.3)
        pyautogui.write('Save')
        time.sleep(0.3)
        pyautogui.press('escape')
        time.sleep(0.2)
        pyautogui.press('enter')
        time.sleep(0.5)
        
        pyautogui.hotkey('ctrl', 'w')  # Close the active Chrome tab
        time.sleep(0.5)

    print("\n🎉 Synchronization complete!")

if __name__ == "__main__":
    run_keyboard_sync("marked_catalog.tsv")
